Exploratory data analysis
vnepveu/regression_pipeline pull request #3
Opened 2020-11-16 10:58 UTC by vnepveu

2020-11-16 13:02 UTC, robincourant requested changes
- Do the same notebook with the other dataset
- Put the two notebook in one directory
- Download the dataset folder on the drive and use the same path and file names !
- Fix little issues

2020-11-16 13:02 UTC, robincourant commented on eda_housing.ipynb
> +    "print(df.head())\n",
Use `display` instead of `print`.

2020-11-16 13:02 UTC, robincourant commented on eda_housing.ipynb
> +}
Add a correlation matrix plot like [this](http://jamesmarquezportfolio.com/correlation_matrices_in_r.html#.WP6WeFB-BPd.facebook).

2020-11-16 13:02 UTC, robincourant commented on eda_housing.ipynb
> +    "# PLot the correlation of variables\n",
Typo : "PLot".

2020-11-16 13:02 UTC, robincourant commented on eda_housing.ipynb
> +    "import seaborn as sb\n",
Add to requirements.

2020-11-16 13:02 UTC, robincourant commented on eda_housing.ipynb
> +    "df = load_dataset(\"housing_data.csv\")\n",
Add a path variable, and please load the dataset folder on the drive in order to have same files and path.

2020-11-16 22:00 UTC, vnepveu commented on eda_housing.ipynb
> +}
Quite impossible except by crafting, graph by graph, the grid plot. The function in link in an R package.

2020-12-03 18:40 UTC, vnepveu commented
@robincourant

2020-12-04 11:10 UTC, merged